In [ ]:
!pip3 install bs4

Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4) (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4) (2.4.1)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1256 sha256=f9ecb3c704bc2e5490fce45e990e3ef2a16da12b40c3a9854035b04fbb59dce2
  Stored in directory: /root/.cache/pip/wheels/25/42/45/b773edc52acb16cd2db4cf1a0b47117e2f69bb4eb300ed0e70
Successfully built bs4
Installing collected packages: bs4
Successfully installed bs4-0.0.1

In [ ]:
!pip3 install bs4
from bs4 import BeautifulSoup
import requests
import pandas as pd

Requirement already satisfied: bs4 in /usr/local/lib/python3.10/dist-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4) (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4) (2.4.1)

### Bir sayfadan veri toplama

In [ ]:
# Bu, verileri almak istediğimiz web sayfasının url'sidir

url = 'https://bilimgenc.tubitak.gov.tr/bilim-genc-tv'

In [ ]:
# Burada bir GET isteği göndermek için requests kitaplığını kullanıyoruz
# belirtilen URL'ye bir yanıt alın
# 200 statüsünü alırsak, her şey yolunda gitti ve sayfa hazır demek

response = requests.get(url)
print(response)

<Response [200]>

In [ ]:
# Yanıt metnini siteden iletiyoruz (response.text)
# Kullanılacak ayrıştırıcıyı belirtin ("lxml"),
# HTML kodunu daha fazla analiz etmek için bir BeautifulSoup nesnesi oluşturduk

bs = BeautifulSoup(response.text,"lxml")
print(bs)

<!DOCTYPE html>
<html dir="ltr" lang="tr" prefix="content: http://purl.org/rss/1.0/modules/content/  dc: http://purl.org/dc/terms/  foaf: http://xmlns.com/foaf/0.1/  og: http://ogp.me/ns#  rdfs: http://www.w3.org/2000/01/rdf-schema#  schema: http://schema.org/  sioc: http://rdfs.org/sioc/ns#  sioct: http://rdfs.org/sioc/types#  skos: http://www.w3.org/2004/02/skos/core#  xsd: http://www.w3.org/2001/XMLSchema# ">
<head>
<meta charset="utf-8"/>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-DKESN3MWM1"></script>
<script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments)};gtag("js", new Date());gtag("set", "developer_id.dMDhkMT", true);gtag("config", "G-DKESN3MWM1", {"groups":"default","page_placeholder":"PLACEHOLDER_page_location","allow_ad_personalization_signals":false});</script>
<link href="http://bilimgenc.tubitak.gov.tr/bilim-genc-tv" rel="canonical"/>
<meta content="RQ_4rW5-3IY_8W6xNoOpwWOtOf3sOZBe-emQmO-5qpI" name="google-site-verification"/>
<meta content="Drupal 9 (https://www.drupal.org)" name="Generator"/>
<meta content="width" name="MobileOptimized"/>
<meta content="true" name="HandheldFriendly"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="/sites/default/files/favicon_0.ico" rel="icon" type="image/vnd.microsoft.icon"/>
<title>Bilim Genç Tv | Bilim Genc | TÜBİTAK Bilim Genç</title>
<link href="/sites/default/files/css/css_chgIOMCsHOXBufKwqQePO7fNPQfQsXusNjAvSYG3TCk.css" media="all" rel="stylesheet"/>
<link href="/sites/default/files/css/css_6kYEmTbdEljO93-_K_Le_gxVUsCLEkbe_EEmbvikGSc.css" media="all" rel="stylesheet"/>
<link href="/sites/default/files/css/css_2uGo9oBFMjRQ1EurS7frYpM-h1GQBrf3cNeha3znjhc.css" media="all" rel="stylesheet"/>
<link href="/sites/default/files/css/css_qd0mJBhhC-QjaBFsC37P3PRoCctl6uVes9kBFGDMK3U.css" media="all" rel="stylesheet"/>
<link href="//cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" media="all" rel="stylesheet"/>
<link href="//fonts.googleapis.com/icon?family=Material+Icons" media="all" rel="stylesheet"/>
<link href="/sites/default/files/css/css_qR-JbwVYeG82RXmuw1A-aqmT8zlh26_rlULpV_8l9nY.css" media="all" rel="stylesheet"/>
<link href="/sites/default/files/css/css_Qq73Q03NEIg0UkqO1XB6YTj4j3LO3F5DdCkcxVyGC7M.css" media="all" rel="stylesheet"/>
<script src="/themes/gin/dist/js/init.js?rycmzu"></script>
<script src="/sites/default/files/js/js_pJBs_U5CFeW43rfMO4MmmpBhEM0fX5cxZigDLLHuc5Q.js"></script>
</head>
<body class="path-bilim-genc-tv" data-gin-accent="blue" data-gin-focus="gin" data-gin-layout-density="default">
<script crossorigin="anonymous" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
<header class="header sticky-top">
<div class="container">
<div class="row header-fixed-mobile">
<div class="col-lg-3 d-flex justify-content-center align-items-center border-right border-bottom login-area">
<a href="/"><img alt="logo" class="header-logo-img" src="/themes/bilim_genc_theme/assets/img/bilim-genc-logo2.svg"/></a>
</div>
<div class="col-lg-9 d-flex bg-white header-mobile">
<div class="mobile-menu-icon mobile-menu" id="menuBtn">
<img alt="Menü" src="/themes/bilim_genc_theme/assets/icons/mobile-sidebar.svg" width="25"/>
</div>
<div class="mobile-sidenav" id="sideNav">
<div class="d-flex justify-content-center align-items-center mt-4">
<a class="btn btn-primary mr-4 text-white" href="/user/login">Giriş yap</a>
<a class="btn btn-white" href="/user/register">Üye ol</a>
</div>
<ul class="list-unstyled">
<li onclick="window.location.href='/'">
<img alt="Anasayfa" class="login-home" height="auto" src="/themes/bilim_genc_theme/assets/icons/home-icon.svg" width="20"/>
<span class="ml-2 mt-3">
<b>Anasayfa</b>
</span>
</li>
</ul>
<div class="mobile-menu-subject">
<div class="col-lg-12 mt-4 d-flex justify-content-center">
<div class="col-lg-4">
<a class="profile-subject-link" href="/populer-bilim">
<div class="profile-subject">
<img alt="Popüler Bilim" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/populer-bilim2.svg"/>
<p class="profile-subject-title">Popüler Bilim</p>
</div>
</a>
</div>
<div class="col-lg-4">
<a class="profile-subject-link" href="/soru-cevap">
<div class="profile-subject">
<img alt="Soru - Cevap" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/soru-cevap2.svg"/>
<p class="profile-subject-title">Soru - Cevap</p>
</div>
</a>
</div>
<div class="col-lg-4">
<a class="profile-subject-link" href="/tasarla-ve-yap">
<div class="profile-subject">
<img alt="Tasarla ve Yap" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/tasarla-yap2.svg"/>
<p class="profile-subject-title">Tasarla ve Yap</p>
</div>
</a>
</div>
</div>
<div class="col-lg-12 mt-3 d-flex justify-content-center">
<div class="col-lg-4">
<a class="profile-subject-link" href="/deneyler">
<div class="profile-subject">
<img alt="Deneyler" class="mobile-menu-icon deney" src="/themes/bilim_genc_theme/assets/icons/deneyler2.svg"/>
<p class="profile-subject-title">Deneyler</p>
</div>
</a>
</div>
<div class="col-lg-4">
<a class="profile-subject-link" href="/bilim-genc-tv">
<div class="profile-subject">
<img alt="Bilim Genç TV" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/bilim-genc-tv2.svg"/>
<p class="profile-subject-title">Bilim Genç TV</p>
</div>
</a>
</div>
<div class="col-lg-4">
<a class="profile-subject-link" href="/gokbilim">
<div class="profile-subject">
<img alt="Gökbilim" class="mobile-menu-icon gokbilim" src="/themes/bilim_genc_theme/assets/icons/gok-bilim2.svg"/>
<p class="profile-subject-title">Gökbilim</p>
</div>
</a>
</div>
</div>
<div class="col-lg-12 mt-3 d-flex justify-content-center">
<div class="col-lg-4">
<a class="profile-subject-link" href="/yeryuzu">
<div class="profile-subject">
<img alt="Yeryüzü" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/yeryuzu2.svg"/>
<p class="profile-subject-title">Yeryüzü</p>
</div>
</a>
</div>
<div class="col-lg-4">
<a class="profile-subject-link" href="/sesli-yayin">
<div class="profile-subject">
<img alt="Sesli Yayın" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/sesli-yayin1.svg"/>
<p class="profile-subject-title">Sesli Yayın</p>
</div>
</a>
</div>
<div class="col-lg-4">
<a class="profile-subject-link" href="/bilim-cizgi">
<div class="profile-subject">
<img alt="Bilim Çizgi" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/bilim-cizgi.svg"/>
<p class="profile-subject-title">Bilim Çizgi</p>
</div>
</a>
</div>
</div>
<div class="col-lg-12 mt-3 d-flex justify-content-center">
<div class="col-lg-4">
<a class="profile-subject-link" href="/periyodik-tablo">
<div class="profile-subject">
<img alt="Periyodik Tablo" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/periyodik-tablo-icon.svg"/>
<p class="profile-subject-title">Periyodik Tablo</p>
</div>
</a>
</div>
<div class="col-lg-4">
<a class="profile-subject-link" href="/bunları-biliyor-musunuz">
<div class="profile-subject">
<img alt="Yeryüzü" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/bunlari-biliyormuydunuz.svg"/>
<p class="profile-subject-title text-center">
               Bunu Biliyor muydunuz?
           </p>
</div>
</a>
</div>
<div class="col-lg-4">
<a class="profile-subject-link" href="/konular/yarismalar">
<div class="profile-subject">
<img alt="Yarışmalar" class="mobile-menu-icon" src="/themes/bilim_genc_theme/assets/icons/yarismalar.svg"/>
<p class="profile-subject-title">Yarışmalar</p>
</div>
</a>
</div>
</div>
</div>
<ul class="list-unstyled">
<li class="" data-target="#collapsibleNavbar2" data-toggle="collapse">
<a class="text-decoration-none d-block" href="#">
<img alt="Popüler Bilim" height="auto" src="/themes/bilim_genc_theme/assets/icons/bilim-genc-icon.svg" width="20"/>
<span class="ml-2 mt-3" style="font-size: 16px">Bilim Genç' i Tanıyın</span>
</a>
</li>
<div class="collapse navbar-collapse" id="collapsibleNavbar2">
<ul class="navbar-nav">
<li class="nav-item mt-0 mb-0">
<a class="nav-link collapse-menu" href="/bilim-genc-hakkinda" style="font-size: 16px">- Bilim Genç Hakkında</a>
</li>
<li class="nav-item mt-0 mb-0">
<a class="nav-link collapse-menu" href="/ekibimiz" style="font-size: 16px">- Ekibimiz</a>
</li>
<li class="nav-item mt-0 mb-0">
<a class="nav-link collapse-menu" href="/icerik-kullanim-sartlari" style="font-size: 16px">- İçerik Kullanım Şartları</a>
</li>
<li class="nav-item mt-0 mb-0">
<a class="nav-link collapse-menu" href="/iletisim" style="font-size: 16px">- İletişim</a>
</li>
</ul>
</div>
<li>
<p class="text-center">Bilim Genç TÜBİTAK’ın dijital ortamda ücretsiz popüler bilim yayınıdır.</p>
</li>
</ul>
</div>
<div class="header-logo mobile-header-logo">
<a href="/"><img alt="logo" class="header-logo-img" src="/themes/bilim_genc_theme/assets/img/bilim-genc-logo2.svg" width="50px"/></a>
</div>
<div class="form-control header-serach" style="border: 0px solid #eee !important">
<div class="form-group position-relative mt-3 d-flex" style="background-color: #f8f8fb !important; border-radius: 0.75rem">
<input class="form-control rounded-1 shadow-none" id="search_text" placeholder="Bilim Genç'te ara" style="background-color: transparent !important" type="text"/>
<img alt="Arama" class="mr-3 btn-open-modal cursor-pointer" id="search_btn" src="/themes/bilim_genc_theme/assets/icons/search-icon.svg"/>
<div class="d-none" data-backdrop="false" data-target="#modal-fullscreen-xl" data-toggle="modal" id="modal-fullscreen-xl-btn"></div>
</div>
</div>
<div class="col-lg-3 d-flex justify-content-center align-items-center login-area">
<a class="btn btn-primary btn-border btn-login mr-4 mb-1 cursor-pointer" href="/user/login">Giriş yap</a>
</div>
</div>
</div>
</div>
<div class="mobile-footer w-100">
<div class="row">
<div class="col-lg-12 d-flex">
<div class="col-lg-4 d-flex justify-content-center align-items-center mt-3 mb-3">
<a href="/"><div class="mobile-icon-home"></div>
</a>
</div>
<div class="col-lg-4 d-flex justify-content-center align-items-center mt-3 mb-3">
<a id="mobile-search-button"><div class="mobile-search"></div>
</a>
</div>
<div class="col-lg-4 d-flex justify-content-center align-items-center mt-3 mb-3">
<a onclick="shareModalLink()"><div class="mobile-share"></div>
</a>
</div>
<div class="col-lg-4 d-flex justify-content-center align-items-center mt-3 mb-3">
<a href="/user/login"><div class="mobile-account"></div>
</a>
</div>
</div>
</div>
</div>
</header>
<script>
  $("#search_btn").click(() => {
    goToSearch();
  });

  $("#mobile-search-button").click(() => {
    goToSearch(true);
  });

  $("#search_text").keypress(function (event) {
    if (event.key === "Enter") {
      goToSearch();
    }
  });
  function goToSearch(mobile = false) {
    if (mobile) {
      window.location.href = `/search/all/allContent?view=mobile`;
    } else {
      let search_text = $("#search_text").val().trim();
      if (search_text == "") {
        search_text = "allContent";
      }
      window.location.href = `/search/all/${search_text}`;
    }
  }
</script>
<!-- HEADER END -->
<!-- MAIN START -->
<div class="container">
<div class="row">
<!-- SIDEBAR START -->
<div class="col-lg-3 border-right pr-0 sidebar-mobile d-lg-block d-none">
<div class="container pr-0 sidebar-sticky sticky-top">
<div class="sidebar border-bottom" id="side_nav">
<ul class="list-unstyled">
<li class="active">
<a class="text-decoration-none px-3 py-2 d-block" href="/populer-bilim">
<img alt="Popüler Bilim" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/populer-bilim2.svg"/>
				Popüler Bilim</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/soru-cevap">
<img alt="Soru - Cevap" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/soru-cevap2.svg"/>
				Soru - Cevap</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/tasarla-ve-yap">
<img alt="Tasarla ve Yap" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/tasarla-yap2.svg"/>
				Tasarla ve Yap</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/deneyler">
<img alt="Deneyler" class="side_nav_icon deney-icon" src="/themes/bilim_genc_theme/assets/icons/deneyler2.svg"/>
				Deneyler</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block active" href="/bilim-genc-tv">
<img alt="Bilim Genç TV" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/bilim-genc-tv2.svg"/>
				Bilim Genç TV</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/konular/yarismalar">
<img alt="Yarışmalar" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/yarismalar.svg"/>
				Yarışmalar
			</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/gokbilim">
<img alt="Gökbilim" class="side_nav_icon gokbilim-icon" src="/themes/bilim_genc_theme/assets/icons/gok-bilim2.svg"/>
				Gökbilim</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/yeryuzu">
<img alt="Yeryüzü" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/yeryuzu2.svg"/>
				Yeryüzü</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/sesli-yayin">
<img alt="Sesli Yayın" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/sesli-yayin1.svg"/>
				Sesli Yayın</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/bilim-cizgi">
<img alt="Bilim Çizgi" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/bilim-cizgi.svg"/>
				Bilim Çizgi
			</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/bunları-biliyor-musunuz">
<img alt="Bunu Biliyor muydunuz?" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/bunlari-biliyormuydunuz.svg"/>
				Bunu Biliyor muydunuz?</a>
</li>
<li class="">
<a class="text-decoration-none px-3 py-2 d-block" href="/periyodik-tablo">
<img alt="Periyodik Tablo" class="side_nav_icon" src="/themes/bilim_genc_theme/assets/icons/periyodik-tablo-icon.svg"/>
				Periyodik Tablo</a>
</li>
</ul>
</div>
<div class="sidebar" id="side__nav">
<ul class="list-unstyled">
<li class="" data-target="#desktopsidebar" data-toggle="collapse">
<a class="text-decoration-none px-3 py-2 d-block cursor-pointer">
<img alt="Popüler Bilim" height="auto" src="/themes/bilim_genc_theme/assets/icons/bilim-genc-icon.svg" width="20"/>
        Bilim Genç' i Tanıyın
      </a>
</li>
<div class="collapse navbar-collapse" id="desktopsidebar">
<ul class="navbar-nav">
<li class="nav-item">
<a class="nav-link collapse-menu" href="/bilim-genc-hakkinda">- Bilim Genç Hakkında</a>
</li>
<li class="nav-item">
<a class="nav-link collapse-menu" href="/ekibimiz">- Ekibimiz</a>
</li>
<li class="nav-item">
<a class="nav-link collapse-menu" href="/icerik-kullanim-sartlari">- İçerik Kullanım Şartları</a>
</li>
<li class="nav-item">
<a class="nav-link collapse-menu" href="/iletisim">- İletişim</a>
</li>
</ul>
</div>
<li class="mt-3 ml-3">
<p class="copyright">Bilim Genç TÜBİTAK’ın dijital ortamda ücretsiz popüler bilim yayınıdır.</p>
</li>
</ul>
</div>
</div>
</div>
<!-- SIDEBAR END -->
<div class="col-12 col-lg-9 mt-3" id="main">
<!-- STORY AREA START -->
<div class="region region-content-header">
<div class="views-element-container" id="block-views-block-bilim-genc-header-story-area-block-1">
<div><div class="view view-bilim-genc-header-story-area view-id-bilim_genc_header_story_area view-display-id-block_1 js-view-dom-id-fdef9ebc58d269f6413c3d10b1f2be8aa0c397adc0ee0e9c5c85c13a6fe5235b">
<div class="view-content">
<div class="story-area mx-2 d-flex">
<div class="views-field views-field-nothing"><span class="field-content">
<div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-matematik-sorusu-agustos-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/matematik_sorusu_a%C4%9Fustos.jpg?itok=ICsA9eB7"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Matematik Sorusu - Ağustos 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div></span></div><div class="views-field views-field-nothing"><span class="field-content">
<div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-matematik-sorusunu-dogru-cozenler-temmuz-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/temmuz-matematik_cevab%C4%B1.jpg?itok=vcoWg0x4"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Matematik Sorusunu Doğru Çözenler – Temmuz 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div></span></div><div class="views-field views-field-nothing"><span class="field-content">
<div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/satranc-agustos-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/satranc%20a%C4%9Fustos%202023%20sorusu.jpg?itok=GFAUcaaW"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Satranç - Ağustos 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div></span></div><div class="views-field views-field-nothing"><span class="field-content">
<div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-sifrebilim-sorusu-agustos-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/sifrebilim_agustos_1.jpg?itok=CA8eGIq5"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Şifrebilim Sorusu - Ağustos 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div></span></div><div class="views-field views-field-nothing"><span class="field-content">
<div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-sifrebilim-sorusunun-cevabi-temmuz-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/sifre_bilim_temmuz_0.jpg?itok=E00CSbzv"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Şifrebilim Sorusunun Cevabı - Temmuz 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>

In [ ]:
# Burada sayfadaki tüm <div class="article-card best-article-card mb-4 img-bottom-overlay"> öğelerini arıyoruz
# Bunları temp değişkeninde sakladık. Bunlar, toplamak istediğimiz sayfadaki tüm haber sayfalarıdır.

temp = bs.find_all('div', 'article-card best-article-card mb-4 img-bottom-overlay')
print(temp)

[<div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-matematik-sorusu-agustos-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/matematik_sorusu_a%C4%9Fustos.jpg?itok=ICsA9eB7"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Matematik Sorusu - Ağustos 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-matematik-sorusunu-dogru-cozenler-temmuz-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/temmuz-matematik_cevab%C4%B1.jpg?itok=vcoWg0x4"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Matematik Sorusunu Doğru Çözenler – Temmuz 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/satranc-agustos-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/satranc%20a%C4%9Fustos%202023%20sorusu.jpg?itok=GFAUcaaW"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Satranç - Ağustos 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-sifrebilim-sorusu-agustos-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/sifrebilim_agustos_1.jpg?itok=CA8eGIq5"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Şifrebilim Sorusu - Ağustos 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-sifrebilim-sorusunun-cevabi-temmuz-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/sifre_bilim_temmuz_0.jpg?itok=E00CSbzv"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Şifrebilim Sorusunun Cevabı - Temmuz 2023</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/visne-eksiyken-neden-kiraz-tatlidir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/vi%C5%9Fne.jpg?itok=gKcgkRwd"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Vişne Ekşiyken Neden Kiraz Tatlıdır?</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/soru-cevap2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/chatgptyi-kullanirken-dikkatli-olmaniz-gereken-3-risk">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/robotik%20kol.jpg?itok=YDFzR9sj"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">ChatGPT’yi Kullanırken Dikkatli Olmanız Gereken 3 Risk</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/populer-bilim2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/kuslarin-gagasi-neden-birbirinden-farkli">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/ku%C5%9Flar.jpg?itok=jOZv0T9W"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Kuşların Gagası Neden Birbirinden Farklı?</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/soru-cevap2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/pil-kim-ne-zaman-icat-etti">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/pil.jpg?itok=khzxQhcB"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Pil: Kim, Ne Zaman İcat Etti? </p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/populer-bilim2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/chatgpt-nedir-nasil-kullanilir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/chat%20gpt%20nedir_0.png?itok=p78w1f4u"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">ChatGPT Nedir? Nasıl Kullanılır?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43525" id="nodeLike_43525">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43525" id="nodeSaveContent_43525">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/haberler" hreflang="tr">Haberler</a></span>
                  • 02-03-2023</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/bir-metni-chatgptnin-hazirladigi-anlasilabilir-mi">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/chatgpt_metin_tespit.jpg?itok=A8tC-aom"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Bir Metni ChatGPT’nin Hazırladığı Anlaşılabilir mi?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43601" id="nodeLike_43601">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43601" id="nodeSaveContent_43601">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/soru-cevap" hreflang="tr">Soru - Cevap</a></span>
                  • 19-04-2023</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/yeryuzu-turkiyenin-zehirli-orumcekleri">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/ugurbocegi_orumcegi1_1.jpg?itok=milbfH2v"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Türkiye’nin Zehirli Örümcekleri</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43361" id="nodeLike_43361">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43361" id="nodeSaveContent_43361">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/yeryuzu" hreflang="tr">Yeryüzü</a></span>
                  • 10-07-2019</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/gelecekteki-tehlike-su-kitligi">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/su_kitligi.jpg?itok=l8usu7pE"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Gelecekteki Tehlike: Su Kıtlığı</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_39115" id="nodeLike_39115">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_39115" id="nodeSaveContent_39115">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/haberler" hreflang="tr">Haberler</a></span>
                  • 22-03-2021</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/turkiyenin-ilk-uzay-yolcularini-taniyalim-alper-gezeravci-kimdir-tuva-cihangir-atasever">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/alper%20gezeravc%C4%B1%20ve%20tuva%20cihangir%20atasever%20kimdir_0.jpg?itok=dBcRQk3v"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Türkiye’nin İlk Uzay Yolcularını Tanıyalım: Alper Gezeravcı Kimdir? Tuva Cihangir Atasever Kimdir?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43628" id="nodeLike_43628">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43628" id="nodeSaveContent_43628">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/haberler" hreflang="tr">Haberler</a></span>
                  • 12-05-2023</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/bakteri-ve-virus-arasinda-ne-fark-var">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/bakteri_ve_virus_arasindaki_farklar_nelerdir_0.jpg?itok=qfM8JH6u"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Bakteri ve Virüs Arasında Ne Fark Var?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_24905" id="nodeLike_24905">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_24905" id="nodeSaveContent_24905">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/soru-cevap" hreflang="tr">Soru - Cevap</a></span>
                  • 10-04-2020</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/imposter-sendromu-sahtekar-degilsiniz">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/imposter_sahtekarlik_sendromu_0.png?itok=Q4Wgyqyq"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">İmposter Sendromu: Sahtekâr Değilsiniz!</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_40603" id="nodeLike_40603">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_40603" id="nodeSaveContent_40603">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/haberler" hreflang="tr">Haberler</a></span>
                  • 29-09-2021</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/satranc-haziran-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/satranc%20haziran%202023%20sorusu.jpg?itok=GbhNIqRn"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Satranç - Haziran 2023</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43662" id="nodeLike_43662">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43662" id="nodeSaveContent_43662">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/konular/ayin-satranc-problemi" hreflang="tr">Satranç</a></span>
                  • 03-06-2023</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-sifrebilim-sorusu-haziran-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/sifrebilim_haziran.jpg?itok=BPqNsCeb"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Şifrebilim Sorusu - Haziran 2023</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43657" id="nodeLike_43657">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43657" id="nodeSaveContent_43657">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/duyurular" hreflang="tr">Duyurular</a></span>
                  • 02-06-2023</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-matematik-sorusu-haziran-2023">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/matematik%20sorusu_haziran.jpg?itok=sGmWV2qE"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Matematik Sorusu - Haziran 2023</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43651" id="nodeLike_43651">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43651" id="nodeSaveContent_43651">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/ayin-matematik-sorusu" hreflang="tr">Ayın Matematik Sorusu</a></span>
                  • 01-06-2023</p>
</div>
</div>]

In [7]:
# "News" ve "links" anahtarlarına sahip bir sözlük oluşturuyoruz,
# Bu sözlük sırasıyla haber başlıkları ve haber bağlantılarını içerecektir.

dict_news = {"news": [], "links": []}

for i in temp:
    news_text = i.find('p', 'card-text')
    news_link = i.find('a').get('href')
    dict_news["news"].extend(news_text)
    dict_news["links"].append(url + news_link)

NameError: name 'temp' is not defined

In [13]:
# Burada bir veri çerçevesi oluşturmak için pandas kütüphanesini kullanıyoruz
# dict_news sözlüğündeki "haberler" ve "bağlantılar" sütunlarına sahip olacak
# Bu veri çerçevesi toplanan haber verilerini içerecektir

df_news = pd.DataFrame(dict_news, columns=["news", "links"])

In [14]:
# Bu, çıktı kolaylığı içindir.
# Toplanan bilgileri herhangi bir yapıda saklayabilirsiniz

df_news

,news,links
0,Işık Kirliliği Nedir? Nasıl Önlenir?,https://bilimgenc.tubitak.gov.tr/makale/isik-k...
1,İklim Değişikliği Çözümleri Ters Tepebilir mi?,https://bilimgenc.tubitak.gov.tr/makale/iklim-...
2,Güneşlenme ile İlgili Doğru Bilinen Yanlışlar,https://bilimgenc.tubitak.gov.tr/makale/gunesl...
3,Fethiye Kelebekler Vadisi,https://bilimgenc.tubitak.gov.tr/makale/fethiy...
4,Eylül 2024’te Gökyüzünde Neler Oluyor?,https://bilimgenc.tubitak.gov.tr/makale/eylul-...
...,...,...
63,ChatGPT Nedir? Nasıl Kullanılır?,https://bilimgenc.tubitak.gov.tr/makale/chatgp...
64,Mayoz Bölünme Nedir?,https://bilimgenc.tubitak.gov.tr/mayoz-bolunme...
65,Mitoz Bölünme Nedir?,https://bilimgenc.tubitak.gov.tr/makale/mitoz-...
66,Hayvanlar Kış Uykusuna Neden Yatar?,https://bilimgenc.tubitak.gov.tr/makale/hayvan...
67,Asal Sayı Nedir?,https://bilimgenc.tubitak.gov.tr/makale/asal-s...

## Resimleri toplayın

In [15]:
dict_news = {"news": [], "links": [], "images": []}
url = 'https://bilimgenc.tubitak.gov.tr/bilim-genc-tv'
response = requests.get(url)
bs = BeautifulSoup(response.text,"lxml")
temp = bs.find_all('div', 'article-card best-article-card mb-4 img-bottom-overlay')

print(temp)

[<div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/isik-kirliligi-nedir-nasil-onlenir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/%C4%B1%C5%9F%C4%B1klar%20alt%C4%B1nda%20%C5%9Fehir.jpg?itok=MrXhsRn_"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Işık Kirliliği Nedir? Nasıl Önlenir?</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/populer-bilim2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/iklim-degisikligi-cozumleri-ters-tepebilir-mi">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/g%C3%B6ky%C3%BCz%C3%BC_bulut.jpg?itok=U4bWY-DQ"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">İklim Değişikliği Çözümleri Ters Tepebilir mi?</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/soru-cevap2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/guneslenme-ile-ilgili-dogru-bilinen-yanlislar">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/g%C3%BCne%C5%9Flenen%20k%C4%B1z.jpg?itok=mMw7neVD"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Güneşlenme ile İlgili Doğru Bilinen Yanlışlar</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/populer-bilim2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/fethiye-kelebekler-vadisi">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/Kelebekler%20Vadisi.jpg?itok=c6jSRPNV"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Fethiye Kelebekler Vadisi</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/populer-bilim2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/eylul-2024te-gokyuzunde-neler-oluyor">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/teleskop%20g%C3%B6ky%C3%BCz%C3%BC.jpg?itok=rJs3L_hm"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Eylül 2024’te Gökyüzünde Neler Oluyor?</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-matematik-sorusu-eylul-2024">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/matematik_eyl%C3%BCl.jpg?itok=sKC9DRoG"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Matematik Sorusu - Eylül 2024</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/ayin-matematik-sorusunu-dogru-cozenler-agustos-2024">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/matematik_sorusu_a%C4%9Fustos_0_0_0.jpg?itok=OYmIVlZ3"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Ayın Matematik Sorusunu Doğru Çözenler – Ağustos 2024</p>
</div>
<img alt="" class="story-area-kose-icon" decoding="async" loading="lazy" src="https://bilimgenc.tubitak.gov.tr/themes/bilim_genc_theme/assets/icons/bilim-genc-icon2.svg"/>
</div>
</a>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/2024-lise-ogrencileri-tubitak-bilim-kamplarina-katilim-basvurulari-basladi">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/bilim%20kamplar%C4%B1.jpg?itok=30wS1JMG"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">2024 Lise Öğrencileri TÜBİTAK Bilim Kamplarına Katılım Başvuruları Başladı!</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_44163" id="nodeLike_44163">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_44163" id="nodeSaveContent_44163">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/duyurular" hreflang="tr">Duyurular</a></span>
                  • 01-08-2024</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/okyanus-yili-temali-resim-yarismasi-son-basvuru-tarihi-30-eylul-2024e-uzatilmistir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/900x6600%20uzatmaOKYANUSUN%20ON%20YILI.jpg?itok=6m9oIHJQ"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">“Okyanus On Yılı” Temalı Resim Yarışması Son Başvuru Tarihi 30 Eylül 2024’e Uzatılmıştır!</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_44161" id="nodeLike_44161">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_44161" id="nodeSaveContent_44161">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/duyurular" hreflang="tr">Duyurular</a></span>
                  • 21-08-2024</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/sinir-sistemi-nedir-sinir-sistemini-olusturan-organlar-neler">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/n%C3%B6ron.jpg?itok=MInHpxEm"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Sinir Sistemi Nedir? Sinir Sistemini Oluşturan Organlar Neler?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43798" id="nodeLike_43798">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43798" id="nodeSaveContent_43798">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/soru-cevap" hreflang="tr">Soru - Cevap</a></span>
                  • 16-09-2023</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/gpt-4o-nedir-nasil-kullanilir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/GPT.jpg?itok=IIWFg-Ug"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">GPT-4o Nedir, Nasıl Kullanılır?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_44109" id="nodeLike_44109">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_44109" id="nodeSaveContent_44109">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/haberler" hreflang="tr">Haberler</a></span>
                  • 23-05-2024</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/sora-yapay-zeka-nedir-nasil-kullanilir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/Video%20U%CC%88retebilen%20Yeni%20Bir%20Yapay%20Zeka%CC%82%20Modeli-%20Sora%20.jpg?itok=umtDw_MC"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Sora Yapay Zekâ Nedir? Nasıl Kullanılır?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43994" id="nodeLike_43994">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43994" id="nodeSaveContent_43994">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/haberler" hreflang="tr">Haberler</a></span>
                  • 16-02-2024</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/chatgpt-nedir-nasil-kullanilir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/chat%20gpt%20nedir_0.png?itok=p78w1f4u"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">ChatGPT Nedir? Nasıl Kullanılır?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43525" id="nodeLike_43525">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43525" id="nodeSaveContent_43525">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/haberler" hreflang="tr">Haberler</a></span>
                  • 02-03-2023</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/mayoz-bolunme-nedir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/mayoz_site.jpg?itok=LQEker3m"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Mayoz Bölünme Nedir?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_42529" id="nodeLike_42529">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_42529" id="nodeSaveContent_42529">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/soru-cevap" hreflang="tr">Soru - Cevap</a></span>
                  • 12-07-2022</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/mitoz-bolunme-nedir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/mitoz_bolunme-1.jpg?itok=1lf_rMNy"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Mitoz Bölünme Nedir?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_42472" id="nodeLike_42472">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_42472" id="nodeSaveContent_42472">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/soru-cevap" hreflang="tr">Soru - Cevap</a></span>
                  • 21-06-2022</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/hayvanlar-kis-uykusuna-neden-yatar">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/hayvanlar_kis_uykusu.jpg?itok=tRXXYoOm"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Hayvanlar Kış Uykusuna Neden Yatar?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_20682" id="nodeLike_20682">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_20682" id="nodeSaveContent_20682">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/soru-cevap" hreflang="tr">Soru - Cevap</a></span>
                  • 29-01-2019</p>
</div>
</div>, <div class="article-card best-article-card mb-4 img-bottom-overlay">
<a href="/makale/asal-sayi-nedir">
<div class="card bg-dark text-white article-card">
<img alt="" class="card-img" decoding="async" loading="lazy" src="/sites/default/files/styles/kucuk_manset_image/public/asal_sayilar_0.jpg?itok=lI7ba3-n"/>
<div class="card-img-overlay d-flex flex-column justify-content-end">
<p class="card-text">Asal Sayı Nedir?</p>
</div>
</div>
</a>
<div class="d-flex flex-wrap justify-content-between mt-2 align-items-center">
<div class="article-card-icons d-flex mt-0">
<div class="article-icon d-flex justify-content-between getLikes nodeLike_43008" id="nodeLike_43008">
</div>
<div class="article-icon d-flex justify-content-between getSaveContent nodeSaveContent_43008" id="nodeSaveContent_43008">
</div>
</div>
<p class="article-date mb-0">
<span><a href="/koselerimiz/soru-cevap" hreflang="tr">Soru - Cevap</a></span>
                  • 04-10-2022</p>
</div>
</div>]

In [16]:
for post in temp:
    dict_news["news"].append(post.find('p', 'card-text'))
    dict_news["links"].append(url + post.find('a').get('href'))
    dict_news["images"].append(post.find('img', 'card-img').get('src'))

df_news

,news,links
0,Işık Kirliliği Nedir? Nasıl Önlenir?,https://bilimgenc.tubitak.gov.tr/makale/isik-k...
1,İklim Değişikliği Çözümleri Ters Tepebilir mi?,https://bilimgenc.tubitak.gov.tr/makale/iklim-...
2,Güneşlenme ile İlgili Doğru Bilinen Yanlışlar,https://bilimgenc.tubitak.gov.tr/makale/gunesl...
3,Fethiye Kelebekler Vadisi,https://bilimgenc.tubitak.gov.tr/makale/fethiy...
4,Eylül 2024’te Gökyüzünde Neler Oluyor?,https://bilimgenc.tubitak.gov.tr/makale/eylul-...
...,...,...
63,ChatGPT Nedir? Nasıl Kullanılır?,https://bilimgenc.tubitak.gov.tr/makale/chatgp...
64,Mayoz Bölünme Nedir?,https://bilimgenc.tubitak.gov.tr/mayoz-bolunme...
65,Mitoz Bölünme Nedir?,https://bilimgenc.tubitak.gov.tr/makale/mitoz-...
66,Hayvanlar Kış Uykusuna Neden Yatar?,https://bilimgenc.tubitak.gov.tr/makale/hayvan...
67,Asal Sayı Nedir?,https://bilimgenc.tubitak.gov.tr/makale/asal-s...

## Tüm sayfalardan veri toplayın

In [18]:
dict_news = {"news": [], "links": [], "images": []}
url = 'https://bilimgenc.tubitak.gov.tr/'
pages = ["bilim-genc-tv", "bilim-cizgi", "koselerimiz/haberler", "koselerimiz/tasarla-ve-yap", "koselerimiz/deneyler","koselerimiz/gokbilim"]

for i in pages:
    response = requests.get(url + i + "/")
    bs = BeautifulSoup(response.text, "html.parser")

    temp = bs.find_all('div', 'article-card best-article-card mb-4 img-bottom-overlay')
    for post in temp:
        dict_news["news"].extend(post.find('p', 'card-text'))
        dict_news["links"].append(url[:-1] + post.find('a').get('href'))
        dict_news["images"].append(post.find('img', 'card-img').get('src'))

df_news = pd.DataFrame(dict_news, columns=["news", "links", "images"])
df_news.to_csv("./saved_data_bilimgenc.csv", index=False)

df_news

,news,links,images
0,Işık Kirliliği Nedir? Nasıl Önlenir?,https://bilimgenc.tubitak.gov.tr/makale/isik-k...,/sites/default/files/styles/kucuk_manset_image...
1,İklim Değişikliği Çözümleri Ters Tepebilir mi?,https://bilimgenc.tubitak.gov.tr/makale/iklim-...,/sites/default/files/styles/kucuk_manset_image...
2,Güneşlenme ile İlgili Doğru Bilinen Yanlışlar,https://bilimgenc.tubitak.gov.tr/makale/gunesl...,/sites/default/files/styles/kucuk_manset_image...
3,Fethiye Kelebekler Vadisi,https://bilimgenc.tubitak.gov.tr/makale/fethiy...,/sites/default/files/styles/kucuk_manset_image...
4,Eylül 2024’te Gökyüzünde Neler Oluyor?,https://bilimgenc.tubitak.gov.tr/makale/eylul-...,/sites/default/files/styles/kucuk_manset_image...
...,...,...,...
80,ChatGPT Nedir? Nasıl Kullanılır?,https://bilimgenc.tubitak.gov.tr/makale/chatgp...,/sites/default/files/styles/kucuk_manset_image...
81,Mayoz Bölünme Nedir?,https://bilimgenc.tubitak.gov.tr/mayoz-bolunme...,/sites/default/files/styles/kucuk_manset_image...
82,Mitoz Bölünme Nedir?,https://bilimgenc.tubitak.gov.tr/makale/mitoz-...,/sites/default/files/styles/kucuk_manset_image...
83,Hayvanlar Kış Uykusuna Neden Yatar?,https://bilimgenc.tubitak.gov.tr/makale/hayvan...,/sites/default/files/styles/kucuk_manset_image...
84,Asal Sayı Nedir?,https://bilimgenc.tubitak.gov.tr/makale/asal-s...,/sites/default/files/styles/kucuk_manset_image...